name: Test
on:
  workflow_dispatch:
jobs:
  upload_example_zip:
    runs-on: ubuntu-latest
    name: Upload example results zip
    steps:
      - name: List files
        run: |
          pwd
          ls
          ls ..
          ls

      - name: Create a Zip of example results for docs example
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'example_results.zip'
          path: '../examples/example_results'
